# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=45, null=True)),
                ('nomecompleto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=75, unique=True, verbose_name='email')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=12, null=True)),
                ('orgaoemissor', models.CharField(blank=True, max_length=45, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='default/users')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('anexo', models.ImageField(upload_to='default/documents')),
                ('datahora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('razaosocial', models.CharField(max_length=100)),
                ('nomefantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('verificada', models.BooleanField(default=True)),
                ('ie', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(null=True)),
                ('complemento', models.CharField(max_length=45, null=True)),
                ('pontoreferencia', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
                ('abreviacao', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id_logradouro', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=45, null=True)),
                ('cidade', models.CharField(max_length=20, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('pais', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='default/project')),
                ('website', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoUsuario',
            fields=[
                ('id_relacao_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneEmpresa',
            fields=[
                ('id_telefone_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=11)),
                ('ramal', models.CharField(max_length=4)),
                ('nome_contato', models.CharField(max_length=45)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneUsuario',
            fields=[
                ('id_telefone_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id_tipo_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacao',
            fields=[
                ('id_tipo_relacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacaoEmpresa',
            fields=[
                ('id_tipo_relacao_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefone',
            fields=[
                ('id_tipo_Telefone', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id_usuario_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.Empresa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visao',
            fields=[
                ('id_visao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='id_visao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.Visao'),
        ),
        migrations.AddField(
            model_name='telefoneusuario',
            name='id_tipo_telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.TipoTelefone'),
        ),
        migrations.AddField(
            model_name='telefoneusuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telefoneempresa',
            name='id_tipo_telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.TipoTelefone'),
        ),
        migrations.AddField(
            model_name='relacaousuario',
            name='id_tipo_relacao_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoRelacaoEmpresa'),
        ),
        migrations.AddField(
            model_name='relacaousuario',
            name='id_usuario_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='relacaoempresa',
            name='id_empresa_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoEmpresa'),
        ),
        migrations.AddField(
            model_name='relacaoempresa',
            name='id_relacao_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoRelacaoEmpresa'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.Logradouro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Endereco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoEmpresa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoDocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Endereco'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.TipoUsuario'),
        ),
    ]
