# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_historicaldocumento_historicalrelacaoempresa_historicalrelacaousuario_historicalvisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
