# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('default', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id_startup', models.AutoField(primary_key=True, serialize=False)),
                ('representante', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/subclasses/empresa/', verbose_name='Imagem')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_name', to='default.Empresa')),
            ],
        ),
    ]
